Sample Number,ClassName,Snippet Number,Method,Exist,Description,Full Description
0,NamingEvent,1,NamingEvent,False,,NULL
0,NamingEvent,2,NamingException,False,,NULL
0,NamingEvent,3,NamingListener,False,,NULL
0,NamingEvent,4,NamingEventObject,False,,NULL
0,NamingEvent,5,NamingEventObject.getEventType(),False,,NULL
0,NamingEvent,6,NamingEventObject.getNewValue(),False,,NULL
0,NamingEvent,7,NamingEventObject.getOldValue(),False,,NULL
0,NamingEvent,8,NamingEventObject.getSource(),False,,NULL
0,NamingEvent,9,NamingEventObject.getTimeStamp(),False,,NULL
0,NamingEvent,10,NamingEventObject.getType(),False,,NULL
0,NamingEvent,11,NamingListener.namingChanged(NamingEvent event),False,,NULL
0,NamingEvent,12,NamingListener.namingUnbound(NamingEvent event),False,,NULL
0,NamingEvent,13,NamingListener.namingExceptionThrown(NamingEvent event),False,,NULL
0,NamingEvent,14,NamingListener.namingStarted(NamingEvent event),False,,NULL
0,NamingEvent,15,NamingListener.namingStopped(NamingEvent event),False,,NULL
1,NamingExceptionEvent,1,String getEventName(),False,,NULL
1,NamingExceptionEvent,2,Object getSource(),False,,NULL
1,NamingExceptionEvent,3,NamingException getException(),True,Retrieves the exception that was thrown.,"

getException
public NamingException getException()
Retrieves the exception that was thrown.

Returns:
The exception that was thrown.


"
1,NamingExceptionEvent,4,void dispatch(),False,,NULL
1,NamingExceptionEvent,5,void dispatch(EventObject event),False,,NULL
